# Prefix: Ctrl+a
unbind C-b
set-option -g prefix C-a

# Mouse support
set -g mouse on

# Join/send pane bindings
bind-key j command-prompt -p "join pane from:" "join-pane -s '%%'"
bind-key k command-prompt -p "send pane to:" "join-pane -t '%%'"
